import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes';
import userRoutes from '../modules/users/user.routes';
import propertyRoutes from '../modules/properties/property.routes';
import appointmentRoutes from '../modules/appointments/appointment.routes';
import demandRoutes from '../modules/demands/demand.routes';
import visitRoutes from '../modules/visits/visit.routes';
import messageRoutes from '../modules/messages/message.routes';
import transactionRoutes from '../modules/transactions/transaction.routes';
import ratingRoutes from '../modules/ratings/rating.routes';
import locationRoutes from '../modules/locations/location.routes';
import blogRoutes from '../modules/blog/blog.routes';
import notificationRoutes from '../modules/notifications/notification.routes';
import statsRoutes from '../modules/stats/stats.routes';
import favoriteRoutes from '../modules/favorites/favorite.routes';
import uploadRoutes from '../modules/uploads/upload.routes';
import settingRoutes from '../modules/settings/setting.routes';
import exchangeRateRoutes from '../modules/exchange-rates/exchangeRate.routes';

const router = Router();

router.use(authRoutes);
router.use(userRoutes);
router.use(propertyRoutes);
router.use(appointmentRoutes);
router.use(demandRoutes);
router.use(visitRoutes);
router.use(messageRoutes);
router.use(transactionRoutes);
router.use(ratingRoutes);
router.use(locationRoutes);
router.use(blogRoutes);
router.use(notificationRoutes);
router.use(statsRoutes);
router.use(favoriteRoutes);
router.use(uploadRoutes);
router.use(settingRoutes);
router.use(exchangeRateRoutes);

export default router;
